# Generated by Django 2.2.16 on 2020-09-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='girl',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
